### ISSUE TITLE
Create a directory with a replica of the results of the TFG

### ISSUE THREAD

**Issue by albertocbarrigon** [albertocbarrigon/maxdft#1]
Hay que crear un directorio y poner dentro el código que se usó para obtener los resultados del TFG (alguna gráfica significativa del TFG). También tendrá que tener un fichero tipo "README" que describa cómo obtener esos resultados (cómo compilar el código, etc.).

Así quedara fijado el "punto de partida" del proyecto.

**Comment by adriangomez** [comment]
Hecho hace mucho tiempo...
